### PR TITLE
Use Arachne for types

### PR DESCRIPTION
**Pull request by panesofglass**
I retained `Freya.Types.Http` and `Freya.Types.Http.Cors` for their lenses since they are used across multiple projects. Well, the former is used in two projects. They could still be useful on their own should someone not want the Machine abstraction but still want to use the types with OWIN. /cc @haf @ademar

### CODE REVIEW

**Comment by kolektiv** [comment]
And now `Freya.Types.Http` and `Freya.Types.Http.Cors` have become `Freya.Lenses.Http` and `Freya.Lenses.Http.Cors` as they only contain lenses from the Freya State to the Arachne typed data. Pretty cool, hopefully! And who doesn't love a PR which is -6500ish on the line count! Of course, it's all elsewhere, but... :)

**Comment by panesofglass** [comment]
This is versioned 1.0.0-alpha. Want to make it just 1.0.0?

**Comment by kolektiv** [comment]
Hmmmm. Why not!

**Comment by panesofglass** [comment]
@kolektiv we'll need to bump arachne to 1.0, too. Otherwise, the versions will be weird.

**Comment by kolektiv** [comment]
Yeah that's a fair point, i'll do that in the morning then :)

**Comment by kolektiv** [comment]
I may do the same for Hekate as well, just so that everything is 1.0+

**Pull request merged**
