### PR TITLE
Maybe Merge This!

### PR DESCRIPTION
**Pull request by kolektiv**
An exploratory PR to explore and socialise change scope

### CODE REVIEW

**Comment by panesofglass** [comment]
Why are we renaming lenses again? This is likely v3 either way, but I would love to know why you think they should change.

**Comment by kolektiv** [comment]
That's a very fair question. As much as anything else, I think because the F# style would imply that they should be in this case. They're standalone lenses accessed through a module, (and thus a member module with lowercase naming, like Map.empty and so on) rather than type members, which obey the uppercase convention. I'll admit I'm not totally happy overall, as much as anything because it seems like you're always going to end up with some upper and some lower depending on location, and that seems a bit messy. It's certainly a breaking change, but with lots of others. I'm not sure. If you were to say "Andrew I really think that we should keep the naming as is" then I'd probably listen :)

**Comment by kolektiv** [comment]
OK! So, it's now merge-friendly, and it would be interesting to get this out there as pre-release packages. I've stuck a quick placeholder for 3.0 in the release notes. My brain isn't very good, would that be enough that if this was merged it would build as 3.0.xx pre-release packages? I think it would without a tag, so... :) ?

**Comment by panesofglass** [comment]
You did a lot of the work I was about to attempt tonight. Thanks! As to your question, you can even now try out the pre-release 3.0.0-bxyz packages via the freya-fs org's [AppVeyor NuGet feed](https://ci.appveyor.com/nuget/freya-fs). Merging to master would promote these pre-releases to the nuget.org feed. Tagging publishes a release version. Let's try updating samples with this to make sure everything works, then update docs as we pre-release to NuGet. How does that sound?

**Comment by ForNeVeR** [comment]
Thank you for the question, guys. I'll take a look tonight and check how much I'll need to change to migrate to 3.0.0 (and I don't see any apriory problems with the API changes).

But please don't forget about docs! They are very important for the people who want to use Freya, and keeping them outdated is not a very good idea.

Also you maybe first release the last version of the 2.0 branch with the fixes to `If-Modified-Since` (just so current users could get the bugfix compatible with their existing code).

**Comment by kolektiv** [comment]
Yes I think releasing the latest 2.0.x with the bugfix in is a sensible plan as suggested by @ForNeVeR - @panesofglass do you want to tag a release and go for that? Seems like a good idea.

Agree on the samples, I'll update my fork and see how they look now with the Appveyor bits. I agree it's quite a large change, getting opinions would be good. I might actually go through and add in some compatibility aliases which will be deprecated, and removed in 4.0 - possibly including originally cased lenses, operators, etc. I may even go through and do the same for Aether. That way people should be able to upgrade with relatively minor hassle, but at the cost of warnings in the build - what do people think on that?

**Comment by kolektiv** [comment]
@panesofglass the appveyor build doesn't seem to be working - not containing things from pull requests, although i've gone in and changed that setting so that it should. Still an empty feed, which is odd. Any ideas? :)

**Comment by ForNeVeR** [comment]
@kolektiv I've tried to switch to the new libraries in [my blog project](https://github.com/ForNeVeR/fornever.me), and if you don't mind, I have a small suggestion regarding to the deprecations you made. `Freya.Router.Lenses` was renamed to `Freya.Router.Optics`. Maybe you could leave an alias (`Lenses = Optics`) if it's not too complex? With this alias 100% of my old code will compile with the new Freya.

Regarding the new API: all I had to do was to replace `Lenses` with `Optics` and follow some deprecation warnings (replace `Atom_` with `atom_`, drop `FreyaMachine.toPipeline` etc); that was very helpful and not painful at all. Also I have already made some smoke tests and all of my code seems to be working. I will migrate my "production" right after the release of Freya 3.0.

Overall, this update looks good to me. Nice work, @kolektiv! :+1:

**Comment by kolektiv** [comment]
Oh that's interesting on the Optics = Lenses thing - Optics and Lenses are both AutoOpen (opening `Freya.Router` should automatically get you the optics) so shouldn't make any difference to the end user - I'd assumed... Have you got an example I can see where that was painful? I've got no problem putting in place something to fix it if I can see where it's happening.

**Comment by ForNeVeR** [comment]
Ah, I simply have a module with `open Freya.Router.Lenses`, but without `open Freya.Router`: https://github.com/ForNeVeR/fornever.me/blob/develop/ForneverMind/Posts.fs#L5-L6

If that's not the case you want to support when migrating to 3.0, I have no problems with changing my code. After all, it's the new major version. I wouldn't expect it to be 100% compatible with 2.0 code.

**Comment by kolektiv** [comment]
Ah I see. Yes, in that case I'd probably just change the open to `open Freya.Router` which should be compatible with future changes. Generally speaking I'd expect people to be opening top level modules and additional operator modules only, usually - the rest should then be exposed - I think :)

**Comment by ForNeVeR** [comment]
Okay, as I said, I have no problem with changing that.

**Comment by ForNeVeR** [comment]
But maybe that's a good idea to document that somewhere. For example, should I open `Freya.Machine.Extensions.Http` or just `Freya.Machine.Extensions`? _(I've already checked and I need to explicitly open `Http`.)_

**Comment by kolektiv** [comment]
You're right though, that would be good if it was documented somewhere :)

**Comment by panesofglass** [comment]
For my 2¢, I think it would be nice to alias the renamed lenses/optics and mark them as obsolete so that changes are not necessary. Also, I saw several places where we appear to still have the older, PascalCased naming in Freya.Core and Freya.Machine. Should we fix those, too?

**Comment by panesofglass** [comment]
@kolektiv @ForNeVeR I just tagged a new release version of Freya 2.0.*.

**Comment by panesofglass** [comment]
Now that we have a new 2.0.* release, should we move forward by merging this into master? I'm game, though I would like to know what @ForNeVeR or @pblasucci thinks of the last few commits that add the `ObsoleteAttribute` and keep existing syntax.

**Comment by ForNeVeR** [comment]
@panesofglass I've already compiled my code with the latest two commits included. My [comment](https://github.com/freya-fs/freya/pull/139#issuecomment-160678742) was made after building the whole Freya from @kolektiv fork and referencing that binaries instead of the Nuget ones.

That version works for me, and the deprecation notices are helpful. I think that's the best you can do after such a big refactoring.

**Comment by kolektiv** [comment]
I'm happy enough to merge this as a public PR, now that we've tagged a 2.x with fixes in - if others are! Probably not one to rush through, but it would be good to get it out there (and maybe a 3.x branch for the examples, etc.)

**Comment by panesofglass** [comment]
I'm working on the merge now.

**Pull request merged**
