### PR TITLE
Fix for dictionary lens to cope with null returned values (safer)

### PR DESCRIPTION
**Pull request by kolektiv**
In combination with https://github.com/SuaveIO/suave/pull/358 (fixing https://github.com/SuaveIO/suave/issues/357) this should get to the point where Suave seems to work with Freya! Hopefully this might mean that https://github.com/SuaveIO/suave/pull/350 is sorted...

Which would be rather cool! I'm not sure when the next official release/pre-release of Suave will be for us to test with release packages... If we get a pre-release out too that would be cool. Maybe @haf or @ademar know on the Suave side? :)

### CODE REVIEW

**Comment by panesofglass** [comment]
That's all?!

**Comment by kolektiv** [comment]
That and the fix to Suave (https://github.com/SuaveIO/suave/pull/358). Hopefully that's all! I'm not sure when new Suave binaries will be published, when they are we can do some fuller testing, but early indications are that this seems to have fixed the basic issue. The fix on our side is only to work around what I think is a slight glitch in Suave, but the fix to our side doesn't really do much harm given its localised nature.

**Comment by haf** [comment]
Thanks, I haven't forgotten the code you've PRed and I also believe I need to fix the disposal here: https://github.com/SuaveIO/suave/pull/354 for OWIN for the next release.

Working on it ;) Needed to take yesterday to relax, hence the lack of work from my side.

**Comment by kolektiv** [comment]
Oh I'm not rushing you Henrik, sorry! :) I know that feeling only too well, and thank you for the info on Logary. Yesterday was my first productive day for a while. Really looking forward to getting Suave+Freya working well now, the first time I got it to run it seemed to work pretty well...

**Comment by panesofglass** [comment]
@kolektiv I think it's safe to go ahead and merge this, correct?

**Comment by panesofglass** [comment]
Worth a mention in [RELEASE_NOTES.md](https://github.com/freya-fs/freya/blob/master/RELEASE_NOTES.md#new-in-300---released-tbd)?

**Comment by kolektiv** [comment]
I think it's safe to merge, i'm not sure it's release notes-worthy - it
should be entirely invisible and internal. When Suave has a next release
and we've tested, we'll be more vocal about the Freya on Suave story :)

**Pull request merged**
