### PR TITLE
Tracking develop branch changes against master

### PR DESCRIPTION
**Pull request by panesofglass**

### CODE REVIEW

**Comment by kolektiv** [comment]
Good call, sensible pull to have - useful to be able to track this. Quite a large diff so far!

**Comment by panesofglass** [comment]
@kolektiv, let's merge now and get this out. Reasons:

1. While in develop and not on NuGet, we won't get feedback.
2. Freya is still alpha, so depending on another alpha is fine.
3. Feedback early and often is better than constantly spinning ourselves. :)

**Comment by kolektiv** [comment]
Yeah let's go for it. There's going to be braking changes, but we are in prerelease, and I'm feeling like breaking changes to common areas are getting less common now (and they're usually logical changes to naming rather than massive rethinking of design - generally anyway!)

**Comment by panesofglass** [comment]
@kolektiv, care to write up some `RELEASE_NOTES`?

**Comment by kolektiv** [comment]
I'll take a look this evening - they might be quite extensive!

**Comment by panesofglass** [comment]
I'll go ahead and merge. Let's update the RELEASE_NOTES before we push to NuGet.

**Pull request merged**
