### PR TITLE
Build updates

### PR DESCRIPTION
**Pull request by panesofglass**
- [x] Use paket for NuGet packaging and publishing.
- [x] Use tagged versions for full releases.
- [x] Only publish master branch builds to NuGet.
- [x] Fix Travis CI builds
- [x] Add version to top-level paket.template (meta package) list of dependencies

### CODE REVIEW

**Comment by panesofglass** [comment]
I have asked for help with the AppVeyor integration [here](http://help.appveyor.com/discussions/problems/3326-github-webhooks-requests-return-403). Now, all the Travis builds are failing for this branch, and I don't know why. :(

**Comment by TWith2Sugars** [comment]
Any chance of getting this source linked as well?

**Comment by panesofglass** [comment]
@TWith2Sugars it should be source linked already. See the Publish.Debug task.

**Comment by TWith2Sugars** [comment]
Nice, didn't even see that!

**Pull request merged**
