### PR TITLE
Potential updates

### PR DESCRIPTION
**Pull request by kolektiv**
Some hidden and not-so-hidden changes.

The internals of the router have been completely reworked. This means it is a) more correct b) slightly less efficient in some cases, but this is probably worth it, as it behaves as it would be expected to. It also sets the groundwork for a two phase routing execution to attempt matches against the path, and the path plus query string where one exists (this makes sense as it supports more of the URI Template matching then, much of which is around matching parts of queries, etc.) This isn't there yet, but could now feasibly be added with only a moderate level of pain and swearing.

Lens and State functions under the Freya.* module have been moved, to Freya.Lens.* and Freya.State.* respectively, shortening the names to get, set, map, etc. in line with the raw Lens.get, Lens.set, etc. familiar from Aether. This is a tiny bit more verbose, but enables consistency across libraries without ending up with mammoth function names.

Currently live Freya libraries no longer have a dependency on Chiron, this is reflected in the build, and has been moved solely in to the inspectors.

In Machine, Representation now has a static `empty` property, giving an empty response for convenience in resources.

If released, this should probably be a major ver bump due to the breaking changes for Lens and State functions.

### CODE REVIEW

**Comment by panesofglass** [comment]
This looks really nice! Thank you! What do you reckon it will take to finish adding query string matching to routing?

**Comment by kolektiv** [comment]
In terms of the query string matching, I have some experiments and design to do there - it's certainly non-trivial. First thing is to get the Arachne URI Template library doing more for matching, and then I'll play with some ideas. I might have a go at the URI stuff shortly in fact, once my brain adjusts to the parser code!

**Comment by kolektiv** [comment]
I'm going to go ahead and merge this. I think the changes are reasonable and usable as they are, and I've also updated the dependencies, and eliminated the dependency on FSharp.Core (packaged). This should (at least for now) solve the problems people have been having due to mismatched package versions, etc. (although we need a long term fix for that!)

**Comment by panesofglass** [comment]
Thank you for merging! I had planned to just go ahead with it this week. ;)

**Comment by panesofglass** [comment]
As to the `FSharp.Core` problem, our likely biggest issue was that we required F# 4 and others may be using F# 3. We could probably get away with requiring F# 3 from NuGet, but not F# 4.

**Comment by kolektiv** [comment]
No worries, it fixed a few problems people had! I think the Nuget issue was also about pulling incompatible versions of Aether/Arachne/etc. because the version dependency is basically > x rather than > x && < y with Nuget. Not sure we can do much about that, but we should be doing a SemVer compat thing if we can. My memory of Nuget is too hazy to remember if that will even work however.

Nothing now takes a Nuget dependency on FSharp.Core as that is seemingly likely to cause problems outside of Freya, whereas the Aether/etc. stuff was fairly localised.

**Pull request merged**
